[package]
name = "ic-validator"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19", default-features = false }
hex = "0.4.2"
ic-constants = { path = "../constants" }
ic-interfaces = { path = "../interfaces" }
ic-types = { path = "../types/types" }
ic-crypto = { path = "../crypto" }
ic-crypto-sha = { path = "../crypto/sha" }

[dev-dependencies]
assert_matches = "1.3.0"
base64 = "0.11.0"
hex = "0.4.2"
ic-crypto-sha = { path = "../crypto/sha"}
ic-test-utilities = { path = "../test_utilities" }
maplit = "1.0.2"

[features]
malicious_code = []
