e2e-scalability-suite-test:
  extends:
    - .e2e-test-base-k8s
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: bazel-test-all
      artifacts: false
    - job: guest-os-updateimg-build
      artifacts: false
  artifacts:
    paths:
    - scalability/
  script:
    - |
      # release
      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_download.py \
          --git-rev="$CI_COMMIT_SHA" --remote-path="release" \
          --out="artifacts/release"
      # canisters
      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_download.py \
          --git-rev="$CI_COMMIT_SHA" --remote-path="canisters" \
          --out="artifacts/canisters"

      mkdir -p gitlab-runner-tmp; cd gitlab-runner-tmp

      ls "${CI_PROJECT_DIR}/artifacts/canisters"
      for canister in "${CI_PROJECT_DIR}"/artifacts/canisters/*.gz; do
        pigz -d "${canister}"
      done
      ls "${CI_PROJECT_DIR}/artifacts/canisters"

      for f in ic-admin ic-nns-init ic-prep ic-workload-generator; do
        pigz -d "${CI_PROJECT_DIR}/artifacts/release/$f.gz"
        chmod u+x "${CI_PROJECT_DIR}/artifacts/release/$f"
        ln -sf "${CI_PROJECT_DIR}/artifacts/release/$f" "$f"
      done

      ls -lah

      # Write GIT revision number in artifacts directory, otherwise benchmark suite will
      # attempt to re-download the artifacts from S3 (and the ones from this branch are
      # not there yet)
      git rev-parse HEAD > "${CI_PROJECT_DIR}/artifacts/release/githash"

      cd "${CI_PROJECT_DIR}/scalability"

      # Actual test script, sets up VMs and drives the test.
      pipenv --python 3
      pipenv install -r requirements.txt

      pipenv run python3 "common/tests/e2e-scalability-tests.py" \
          --timeout "$GUEST_OS_TEST_TIMEOUT" \
          --ic_os_version "$CI_COMMIT_SHA" \
          --ic_admin_bin "${CI_PROJECT_DIR}/artifacts/release/ic-admin" \
          --nns_canisters "${CI_PROJECT_DIR}/artifacts/canisters/" \
          --ic_prep_bin "${CI_PROJECT_DIR}/artifacts/release/ic-prep" \
          --install_nns_bin "${CI_PROJECT_DIR}/artifacts/release/ic-nns-init" \
          --artifacts_path "${CI_PROJECT_DIR}/artifacts/release/" \
          --farm_group_name "e2e-scalability-pipeline-${CI_PIPELINE_ID}" \
          --ci_runner_tags "${CI_RUNNER_TAGS}"
