[package]
name = "ic-nervous-system-common"
version = "0.8.0"
edition = "2021"

[lib]
name = "ic_nervous_system_common"
path = "src/lib.rs"

[dependencies]
# This MUST be kept in sync with build-info-build in the [build-dependencies] section!
build-info = { version = "0.0.28", default-features = false, features = [] }

anyhow = "1.0.57"
bytes = "1.0.1"
candid = "0.8.1"
async-trait = "0.1.42"
dfn_core = { path = "../../rust_canisters/dfn_core" }
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_protobuf = { path = "../../rust_canisters/dfn_protobuf" }
ic-base-types = { path = "../../types/base_types" }
ic-crypto-sha = { path = "../../crypto/sha" }
ic-ic00-types = { path = "../../types/ic00_types" }
icp-ledger = { path = "../../rosetta-api/icp_ledger" }
rand = "0.8.4"
rand_chacha = "0.3.1"
rust_decimal = "1.25"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
# This MUST be kept in sync with build-info in the [dependencies] section!
build-info-build = { version="0.0.28", default-features = false, features = [] }

[dev-dependencies]
ic-nns-governance = { path = "../../nns/governance" }
proptest = "1.0"
prost = "0.11.0"
