[package]
name = "ic-sns-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sns"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
base64 = "0.13.0"
bytes = "1.0.1"
candid = "0.8.1"
clap = { version = "3.1.6", features = ["derive"] }
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
dfn_protobuf = { path = "../../rust_canisters/dfn_protobuf" }
hex = "0.4.3"
ic-base-types = { path = "../../types/base_types" }
ic-crypto-sha = { path = "../../crypto/sha" }
ic-nervous-system-common = {path = "../../nervous_system/common"}
ic-nns-constants = { path = "../../nns/constants" }
ic-protobuf = { path = "../../protobuf" }
ic-sns-governance = { path = "../governance" }
ic-sns-init = { path = "../init" }
ic-sns-root = { path = "../root" }
ic-sns-test-utils = { path = "../test_utils" }
ic-sns-wasm = { path = "../../nns/sns-wasm" }
icp-ledger = { path = "../../rosetta-api/icp_ledger" }
maplit = "1.0.2"
on_wire = { path = "../../rust_canisters/on_wire" }
prost = "0.11.0"
rand = "0.8"
regex = "1.5.6"
serde_json = { version = "1.0.79", features = ["std"]}
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.24"
json-patch = "0.2.6"
tempfile = "3.1.0"
url = "2.2.0"
