[package]
name = "ic-replicated-state"
version = "0.8.0"
edition = "2021"

[dependencies]
bitcoin = "0.28.1"
cvt = "0.1.1"
debug_stub_derive = "0.3.0"
ic-btc-types = { path = "../bitcoin/types/public" }
ic-btc-types-internal = { path = "../bitcoin/types/internal" }
ic-base-types = { path = "../types/base_types" }
ic-certification-version = { path = "../canonical_state/certification_version" }
ic-config = { path = "../config" }
ic-constants = { path = "../constants" }
ic-error-types = { path = "../types/error_types" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-protobuf = { path = "../protobuf" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-features = { path = "../registry/subnet_features" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-sys = { path = "../sys" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
ic-wasm-types = { path = "../types/wasm_types" }
lazy_static = "1.4.0"
libc = "0.2.91"
maplit = "1.0.2"
nix = "0.23.0"
rand = "0.8.4"
rand_chacha = "0.3.0"
phantom_newtype = { path = "../phantom_newtype" }
serde = { version = "1.0.99", features = [ "derive" ] }
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
tempfile = "3.1.0"

[dev-dependencies]
criterion = "0.3"
criterion-time = { path = "../criterion_time" }
ic-btc-test-utils = { path = "../bitcoin/test-utils" }
ic-test-utilities = { path = "../test_utilities" }
maplit = "1.0.2"
serde_cbor = "0.11.1"
proptest = "1.0"
prost = "0.11.0"
scoped_threadpool = "0.1.*"

[[bench]]
name = "bench_allocator"
harness = false
