[package]
name = "elastic_common_schema"
version = "0.8.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", default-features = false }
erased-serde = "0.3.11"
hyper = "0.14.18"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.54"
slog = { version = "2.5.2", features = ["nested-values"] }
slog_derive = "0.2.0"
slog-json = { version = "2.3", features = ["nested-values"] }
uuid = { version = "0.8.1", features = ["v4"] }

[dev-dependencies]
anyhow = "1.0.31"
