[package]
name = "ic-nns-handler-root"
version = "0.8.0"
edition = "2021"

[[bin]]
name = "root-canister"
path = "canister/canister.rs"

[[bin]]
name = "upgrade-test-canister"
path = "test_canisters/upgrade_test_canister.rs"

[lib]
path = "src/lib.rs"

[dependencies]
# This MUST be kept in sync with build-info-build in the [build-dependencies] section!
build-info = { version = "0.0.28", default-features = false, features = [] }

candid = "0.8.1"
dfn_candid = {path="../../../rust_canisters/dfn_candid"}
dfn_core = { path = "../../../rust_canisters/dfn_core" }
dfn_macro = { path = "../../../rust_canisters/dfn_macro" }
ic-base-types = {path="../../../types/base_types"}
ic-crypto-sha = {path = "../../../crypto/sha/"}
ic-ic00-types = {path="../../../types/ic00_types"}
ic-nervous-system-common-build-metadata = { path = "../../../nervous_system/common/build_metadata" }
ic-nervous-system-root = { path = "../../../nervous_system/root" }
ic-nns-common ={path="../../common"}
ic-nns-constants ={path="../../constants"}
ic-nns-governance = { path = "../../governance"}
ic-protobuf = { path = "../../../protobuf" }
ic-registry-keys = { path = "../../../registry/keys" }
ic-registry-transport = { path = "../../../registry/transport" }
ic-registry-routing-table = { path = "../../../registry/routing_table" }
on_wire = { path = "../../../rust_canisters/on_wire"}
prost = "0.10.4"
serde = { version = "1.0.99", features = ["derive"] }
serde_bytes = "0.11"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
canister-test = { path = "../../../rust_canisters/canister_test" }
ic-nns-constants ={path="../../constants"}
ic-nns-handler-root-protobuf-generator = { path = "./protobuf_generator" }
ic-nns-test-utils = { path = "../../../nns/test_utils" }
ic-types = { path = "../../../types/types" }
ic-test-utilities = {path="../../../test_utilities"}
ic-test-utilities-compare-dirs = { path = "../../../test_utilities/compare_dirs" }
tempfile = "3.1.0"
on_wire = { path = "../../../rust_canisters/on_wire" }
assert_matches = "1.3.0"
hex = "0.4.2"
lazy_static = "1.4.0"
registry-canister = { path = "../../../registry/canister" }

[build-dependencies]
# This MUST be kept in sync with build-info in the [dependencies] section!
build-info-build = { version="0.0.28", default-features = false, features = [] }
