[package]
name = "ic-fondue"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
edition = "2021"

[dependencies]
anyhow = "1.0"
bincode = "1.2.1"
canister-test = { path = "../rust_canisters/canister_test" }
chrono = { version = "0.4.19", default-features = false }
crossbeam-channel = "0.5.5"
either = "1.6"
flate2 = "1.0.22"
fs_extra = "1.2.0"
futures = "0.3.6"
hex = "0.4.2"
humantime = "2.0"
ic-agent = "=0.22.0"
ic-base-types = { path = "../types/base_types" }
ic-config = { path = "../config" }
ic-crypto-sha = { path = "../crypto/sha" }
ic-interfaces-registry = { path = "../interfaces/registry" }
ic-nns-init = { path = "../nns/init" }
ic-prep = { path = "../prep" }
ic-protobuf = { path = "../protobuf" }
ic-registry-client = { path = "../registry/client"}
ic-registry-client-helpers = { path = "../registry/helpers" }
ic-registry-local-registry = { path = "../registry/local_registry" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-features = { path = "../registry/subnet_features" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-registry-transport = { path = "../registry/transport" }
ic-replica = { path = "../replica" }
ic-test-identity = { path = "../test_utilities/identity" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
lazy_static = "1.4.0"
libc = "0.2.91"
mio = { version = "0.7", features = ["os-poll", "os-ext", "pipe"] }
nix = "0.23.0"
nonblock = "0.1.0"
pico-args = "0.3"
rand = "0.8.3"
rand_chacha = "0.3.0"
regex = "1.5.0"
reqwest = { version = "0.11.1", features = [ "blocking", "json", "multipart", "native-tls" ] }
retain_mut = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_cbor = "0.11.1"
serde_millis = "0.1"
signal-hook = { version = "0.3.6", features = ["iterator"] }
signal-hook-mio = { version = "0.2.0", features = ["support-v0_7"] }
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_trace"] }
slog-async = { version = "2.5", features = ["nested-values"] }
slog-term = "2.6.0"
ssh2 = { git = "https://github.com/dfinity-lab/ssh2-rs", branch = "master" }
tempfile = "3.1"
thiserror = "1.0"
tokio = "1.15.0"
url = "2.1.1"

[dev-dependencies]
ic-test-utilities = { path = "../test_utilities" }
