[package]
name = "ic-crypto-tls-cert-validation"
version = "0.8.0"
edition = "2021"

[dependencies]
########################################################
# Because this crate is used in a canister, we can only
# use dependencies that can be compiled to WebAssembly.
########################################################
chrono = { version = "0.4.19", default-features = false }
hex = "0.4.2"
ic-base-types = { path = "../../../types/base_types" }
ic-crypto-internal-basic-sig-ed25519 = { path = "../../internal/crypto_lib/basic_sig/ed25519" }
ic-crypto-internal-types = { path = "../../internal/crypto_lib/types" }
ic-protobuf = { path = "../../../protobuf" }
ic-types = { path = "../../../types/types" }
x509-parser = { version = "0.9.1" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
dfn_core = { path = "../../../rust_canisters/dfn_core" }

[dev-dependencies]
curve25519-dalek = "3.0.2"
ic-config = { path = "../../../config"}
ic-crypto-node-key-generation = { path = "../../node_key_generation" }
ic-crypto-test-utils = { path = "../../test_utils" }
ic-test-utilities = { path = "../../../test_utilities" }
openssl = "0.10.29"
