[package]
name = "ic-registry-transport"
version = "0.8.0"
edition = "2021"

[dependencies]
candid = "0.8.1"
ic-protobuf = { path = "../../protobuf" }
prost = "0.11.0"
bytes = "1.0.1"
serde = { version = "1.0.99", features = ["derive"] }

[dev-dependencies]
ic-registry-transport-protobuf-generator = { path = "./protobuf_generator" }
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
tempfile = "3.1.0"
